apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://tracelogkit-prometheus:9090
    uid: tracelogkit-prometheus
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://tracelogkit-loki:3100
    uid: tracelogkit-loki
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tracelogkit-tempo:3200
    uid: tracelogkit-tempo
    editable: true

